- hosts: all
  remote_user: root
  gather_facts: no
  tasks:
      - name: Install python
        raw: "apt-get update -y && apt-get install {{ python_package }} -y"
        when: "{{ install_python }}"

- hosts: docker_registry
  remote_user: root
  roles:
      - geerlingguy.apache
      - lexrus.ansible-role-docker
      - role: docker-registry

- hosts: mesos_masters
  remote_user: root
  roles:
      - role: mesos-masters

- hosts: mesos_slaves
  remote_user: root
  roles:
      - lexrus.ansible-role-docker
      - role: mesos-slaves

- hosts: chronos
  remote_user: root
  roles:
      - role: chronos

- hosts: galaxy
  remote_user: root
  pre_tasks:
      - set_fact:
          object_store_directory: "{{ hostvars[groups['nfs_clients'][0]].mountable_dir }}"
  roles:
      - geerlingguy.apache
      - lexrus.ansible-role-docker
      - role: galaxy

- hosts: nfs_server
  remote_user: root
  roles:
      - role: nfs

- hosts: nfs_clients
  remote_user: root
  pre_tasks:
      - set_fact:
          exported_dir: "{{ hostvars[groups['nfs_server'][0]].exported_dir }}"
  roles:
      - nfs-clients
