- fail:
    msg: You need to specify exactly one host to run the executor.
  when: groups.executor|length != 1

- name: Add server name to the apache.conf
  lineinfile:
      dest: "/etc/apache2/apache2.conf"
      regexp: ^ServerName
      line: "ServerName {{ inventory_hostname }}"
      state: present
  notify:
      - restart apache2

- name: Ensure locale is en_US.UTF-8
  lineinfile:
      dest: /etc/default/locale
      regexp: LC_ALL
      line: "LC_ALL=\"en_US.UTF-8\""

- name: Install required packages
  apt:
      name: "{{ item }}"
      state: latest
  with_items:
      - git
      # Galaxy needs python 2.7.
      - python
      - virtualenv
      - postgresql
      - postgresql-contrib
      - python-psycopg2

- name: Clone galaxy repo
  git:
      repo: "{{ galaxy_repo }}"
      dest: "{{ executor_directory }}"
      clone: yes
      version: "{{ galaxy_version }}"
      accept_hostkey: yes

- name: Install extra packages in virtualenv
  pip: name="{{ item }}" virtualenv="{{ executor_directory }}/.venv"
  with_items:
    - watchdog
    - chronos-python

- name: Create postgres user and database
  become: yes
  become_user: postgres
  shell: |
    createuser {{ executor_db_user }}
    createdb {{ executor_db_name }}
    psql -c "ALTER USER {{ executor_db_user }} WITH ENCRYPTED PASSWORD  '{{ executor_db_password }}';"
  tags: postgres

- name: Create object store
  file:
      path: "{{ object_store_directory }}"
      state: directory

- name: Create tool_conf.xml file
  copy:
      remote_src: True
      src: "{{ executor_directory }}/config/tool_conf.xml.sample"
      dest: "{{ executor_directory }}/config/tool_conf.xml"

- name: Setup systemd
  template:
    src: galaxy.ini.j2
    dest: "{{ executor_directory }}/config/galaxy.ini"
    force: yes

- name: Setup job_conf
  template:
    src: job_conf.xml.j2
    dest: "{{ executor_directory }}/config/job_conf.xml"
    force: yes

- name: Setup systemd
  template:
    src: galaxy.service.j2
    dest: "/lib/systemd/system/galaxy.service"
    force: yes

- name: Install Galaxy
  shell: "{{executor_directory}}/run.sh --status | echo OK"

- name: Enable Galaxy in systemd
  shell: "systemctl enable galaxy"
  notify: start galaxy
