- name: Install required packages.
  apt:
      name: "{{ item }}"
      state: installed
  with_items:
      - python
      - python-passlib
      - python-pip
      - apache2
      - apache2-utils

- name: Enable apache2 modules
  shell: "a2enmod {{ item }}"
  with_items:
    - authn_file
    - authn_core
    - authz_groupfile
    - authz_user
    - authz_core
    - auth_basic
    - access_compat
    - headers
    - ssl
    - proxy
    - proxy_http
  notify: restart apache2

- name: Make sure we can use docker_container
  pip:
      name : "{{ item }}"
  with_items:
      - docker-py

- name: Add a user entry
  htpasswd:
      path: "{{ server_root }}/conf/htpasswd"
      name: "{{ registry_username }}"
      password: "{{ registry_password }}"

- name: Run docker registry container.
  docker_container:
      image: registry:2
      name: registry
      ports:
          - "127.0.0.1:5000:5000"
      state: started
      volumes:
          - "/mnt/registry:/var/lib/registry"
      restart_policy: always
